/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Aluno;
import Model.AlunoManager;
import Model.EmprestimoManager;
import Model.Emprestimos;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class ControleDevolucao extends javax.swing.JFrame {
    private ArrayList<Emprestimos> listaEmprestimos;
    private Emprestimos e;
    private GregorianCalendar calen;
    private SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
    /**
     * Creates new form ControleDevolucao
     */
    public ControleDevolucao() {
        initComponents();
        e=new Emprestimos();
        calen=new GregorianCalendar();
        ButLivro1.setVisible(false);
        ButLivro2.setVisible(false);
        lLivro1.setVisible(false);
        lLivro2.setVisible(false);
        lRealizacao.setVisible(false);
        lDevolucao.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        TextMulta.setVisible(false);
        ButPagar.setVisible(false);
        ButAdiar.setVisible(false);
        ButExcluir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lRealizacao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lDevolucao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ButPagar = new javax.swing.JButton();
        TextNome = new javax.swing.JTextField();
        TextMulta = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox();
        lLivro1 = new javax.swing.JLabel();
        lLivro2 = new javax.swing.JLabel();
        ButLivro1 = new javax.swing.JButton();
        ButLivro2 = new javax.swing.JButton();
        ButAdiar = new javax.swing.JButton();
        ButExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução de Alunos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 46, 51), 14), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 217, 217), 8)));
        jPanel1.setMinimumSize(new java.awt.Dimension(375, 356));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lRealizacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lRealizacao.setText("00/00/0000");
        jPanel1.add(lRealizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 234, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 231, -1, 22));

        lDevolucao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lDevolucao.setText("00/00/0000");
        jPanel1.add(lDevolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 234, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Multa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 294, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nome:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 36, -1, -1));

        ButPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coin.png"))); // NOI18N
        ButPagar.setText("Pagar");
        ButPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPagarActionPerformed(evt);
            }
        });
        jPanel1.add(ButPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 274, 149, -1));

        TextNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextNomeKeyPressed(evt);
            }
        });
        jPanel1.add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 33, 427, -1));

        try {
            TextMulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextMulta.setText("00");
        TextMulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(TextMulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 291, 36, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 79, 385, -1));

        lLivro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lLivro1.setText("jLabel1");
        jPanel1.add(lLivro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 137, -1, -1));

        lLivro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lLivro2.setText("jLabel2");
        jPanel1.add(lLivro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 186, -1, -1));

        ButLivro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButLivro1.setText("Devolver");
        ButLivro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLivro1ActionPerformed(evt);
            }
        });
        jPanel1.add(ButLivro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 133, -1, -1));

        ButLivro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButLivro2.setText("Devolver");
        ButLivro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLivro2ActionPerformed(evt);
            }
        });
        jPanel1.add(ButLivro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 182, -1, -1));

        ButAdiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButAdiar.setText("adiar");
        ButAdiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAdiarActionPerformed(evt);
            }
        });
        jPanel1.add(ButAdiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 290, -1, -1));

        ButExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fire.png"))); // NOI18N
        ButExcluir.setText("Excluir");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(ButExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 276, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNomeKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Aluno a=AlunoManager.consultar(TextNome.getText(),"nome");
            if(a!=null){
                TextNome.setText(a.getNome());
                listaEmprestimos=EmprestimoManager.returnaTodos(TextNome.getText());
                jComboBox1.removeAllItems();
                for (Emprestimos listaEmprestimo : listaEmprestimos) {
                    jComboBox1.addItem(listaEmprestimo.getId());
                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum aluno encontrado","Vazio",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_TextNomeKeyPressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(jComboBox1.getItemCount()>0){
            ButExcluir.setVisible(true);
            e=listaEmprestimos.get(jComboBox1.getSelectedIndex());
            if(e.getPendentes()==3 ){
                lLivro1.setText(EmprestimoManager.getLivro(e.getLivro1()));
                lLivro2.setText(EmprestimoManager.getLivro(e.getLivro2()));
                lLivro1.setToolTipText(EmprestimoManager.getLivro(e.getLivro1()));
                lLivro2.setToolTipText(EmprestimoManager.getLivro(e.getLivro2()));
                lLivro1.setVisible(true);
                lLivro2.setVisible(true);
                ButLivro1.setVisible(true);
                ButLivro2.setVisible(true);
            }else if(e.getPendentes()==1){
                lLivro1.setText(EmprestimoManager.getLivro(e.getLivro1()));
                lLivro1.setVisible(true);
                ButLivro1.setVisible(true);
                lLivro2.setVisible(false);
                ButLivro2.setVisible(false);
                lLivro1.setToolTipText(EmprestimoManager.getLivro(e.getLivro1()));
            }else if(e.getPendentes()==2){
                lLivro2.setText(EmprestimoManager.getLivro(e.getLivro2()));
                lLivro2.setVisible(true);
                ButLivro2.setVisible(true);
                lLivro1.setVisible(false);
                ButLivro1.setVisible(false);
                lLivro2.setToolTipText(EmprestimoManager.getLivro(e.getLivro2()));
            }else{
                ButLivro1.setVisible(false);
                ButLivro2.setVisible(false);
                lLivro1.setVisible(false);
                lLivro2.setVisible(false);
            }
            ButAdiar.setVisible(true);
            String data=e.getDatarealizacao();
            data=data.substring(0, 2)+"/"+data.substring(2, 4)+"/"+data.substring(4);
            lRealizacao.setText(data);
            data=e.getDataDevolucao();
            data=data.substring(0, 2)+"/"+data.substring(2, 4)+"/"+data.substring(4);
            lDevolucao.setText(data);
            lRealizacao.setVisible(true);
            lDevolucao.setVisible(true);
            jLabel1.setVisible(true);
            if( e.getMulta()>0){
                jLabel2.setVisible(true);
                TextMulta.setVisible(true);
                ButPagar.setVisible(true);
                if(e.getMulta()>9){
                TextMulta.setText(Integer.toString(e.getMulta()));
                }else{
                    TextMulta.setText("0"+Integer.toString(e.getMulta()));
                }
            }else{
                jLabel2.setVisible(false);
                TextMulta.setVisible(false);
                ButPagar.setVisible(false);
            }
            /*else{  //se não tiver multa calcular multa
                Date tempo;
                Date hoje;
                try {

                    tempo = formato.parse(data);
                    calen=new GregorianCalendar();
                    hoje=calen.getTime();
                    data=formato.format(hoje);
                    hoje=formato.parse(data);
                    if(hoje.after(tempo)){
                        multar();
                        escolhido.setMulta(Integer.parseInt(TextMulta.getText()));
                        EmprestimoManenger.multar(escolhido);
                }else{
                        jLabel2.setVisible(false);
                    TextMulta.setVisible(false);
                    ButPagar.setVisible(false);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(ControleDevolucao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }*/
        }else{
            ButLivro1.setVisible(false);
        ButLivro2.setVisible(false);
        lLivro1.setVisible(false);
        lLivro2.setVisible(false);
        lRealizacao.setVisible(false);
        lDevolucao.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        TextMulta.setVisible(false);
        ButPagar.setVisible(false);
        ButAdiar.setVisible(false);
        ButExcluir.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void ButLivro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLivro1ActionPerformed
        e=listaEmprestimos.get(jComboBox1.getSelectedIndex());
        EmprestimoManager.devolver(e,EmprestimoManager.Livro1Pendente);
        ButLivro1.setVisible(false);
        lLivro1.setVisible(false);
        e.setPendentes(e.getPendentes()-1);
        calen=new GregorianCalendar();
        if(e.getPendentes()==0 && 
                e.getDataDevolucao().equals(formato.format(calen.getTime()).replace("/", ""))){
            new Thread(new Runnable() {
            public void run() {
                EmprestimoManager.contar();
            }
            }).start();
            
        }
        listaEmprestimos.set(jComboBox1.getSelectedIndex(), e);
    }//GEN-LAST:event_ButLivro1ActionPerformed

    private void ButLivro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLivro2ActionPerformed
        e=listaEmprestimos.get(jComboBox1.getSelectedIndex());
        EmprestimoManager.devolver(e,EmprestimoManager.Livro2Pendente);
        ButLivro2.setVisible(false);
        lLivro2.setVisible(false);
        e.setPendentes(e.getPendentes()-2);
        if(e.getPendentes()==0 && 
                e.getDataDevolucao().equals(formato.format(calen.getTime()).replace("/", ""))){
            new Thread(new Runnable() {
            public void run() {
                EmprestimoManager.contar();
            }
            }).start();
        }
        listaEmprestimos.set(jComboBox1.getSelectedIndex(), e);
    }//GEN-LAST:event_ButLivro2ActionPerformed

    private void ButPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPagarActionPerformed
         e=listaEmprestimos.get(jComboBox1.getSelectedIndex());
        e.setMulta(Integer.parseInt(TextMulta.getText()));
        calen= new GregorianCalendar();
        e.setDataPagamento(formato.format(calen.getTime()).replace("/", ""));
        if(EmprestimoManager.pagar(e)){
            jLabel2.setVisible(false);
            TextMulta.setVisible(false);
            ButPagar.setVisible(false);
        }
        
    }//GEN-LAST:event_ButPagarActionPerformed

    private void ButAdiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAdiarActionPerformed
          e=listaEmprestimos.get(jComboBox1.getSelectedIndex());
         calen=new GregorianCalendar();
         int d=7;
         try{
             d=Integer.parseInt(JOptionPane.showInputDialog("Digite o número de dias\nignore se for 7"));
         }catch(NumberFormatException e){
             d=7;
         }
         String h=e.getDataDevolucao();
         if(e.getDataDevolucao().equals(formato.format(calen.getTime()).replace("/", ""))){
             new Thread(new Runnable() {
            public void run() {
                EmprestimoManager.contar();
            }
            }).start();
        }
         h=h.substring(0, 2)+"/"+h.substring(2, 4)+"/"+h.substring(4);
        try {
            calen.setTime(formato.parse(h));
        } catch (ParseException ex) {
            Logger.getLogger(ControleDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
         calen.add(Calendar.DAY_OF_YEAR, d);
         h=formato.format(calen.getTime());
         lDevolucao.setText(h);
         e.setDataDevolucao(h.replace("/",""));
         EmprestimoManager.adiar(e);
        listaEmprestimos.set(jComboBox1.getSelectedIndex(), e);
        
    }//GEN-LAST:event_ButAdiarActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
        int resposta=JOptionPane.showConfirmDialog(null, "Tem certeza que quer deletar?\nSerá excluido permanentemente", "Exclusão", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION) {
            
            String respost=JOptionPane.showInputDialog(null, "Escreva 'deletar' \nignorar maiusculo e minusculo", "Confirmação", JOptionPane.QUESTION_MESSAGE);
            if(respost.equalsIgnoreCase("deletar")){
                e=listaEmprestimos.get(jComboBox1.getSelectedIndex());
                EmprestimoManager.Deletar(e);
                
                jComboBox1.removeAllItems();
                ButLivro1.setVisible(false);
                ButLivro2.setVisible(false);
                lLivro1.setVisible(false);
                lLivro1.setText("");
                lLivro2.setVisible(false);
                lLivro2.setText("");
                lRealizacao.setVisible(false);
                lDevolucao.setVisible(false);
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                TextMulta.setVisible(false);
                ButPagar.setVisible(false);
                ButAdiar.setVisible(false);
                ButExcluir.setVisible(false);
                
            }}
        
    }//GEN-LAST:event_ButExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleDevolucao().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdiar;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButLivro1;
    private javax.swing.JButton ButLivro2;
    private javax.swing.JButton ButPagar;
    private javax.swing.JFormattedTextField TextMulta;
    private javax.swing.JTextField TextNome;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lDevolucao;
    private javax.swing.JLabel lLivro1;
    private javax.swing.JLabel lLivro2;
    private javax.swing.JLabel lRealizacao;
    // End of variables declaration//GEN-END:variables
}
