/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.CadastradorDeLivros;
import Model.EmprestimoManager;
import Model.Livro;
import Model.LivroManager;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class ControleLivro extends javax.swing.JFrame {
    private Livro l;
    /**
     * Creates new form ControleLivro
     */
    public ControleLivro() {
        initComponents();
        ButAlterar.setVisible(false);
        ButExcluir.setVisible(false);
        l=new Livro();
         BoundsPopupMenuListener listener =
        new BoundsPopupMenuListener();
        Lista.addPopupMenuListener( listener );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextTitulo = new javax.swing.JTextField();
        ButListaTitulo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextAutor = new javax.swing.JTextField();
        ButListaAutor = new javax.swing.JButton();
        Lista = new javax.swing.JComboBox();
        ButPesquisa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextEditora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextEdicao = new javax.swing.JFormattedTextField();
        TextQuantidade = new javax.swing.JFormattedTextField();
        ButGravar = new javax.swing.JButton();
        ButAlterar = new javax.swing.JButton();
        ButExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        fileChooser.setDialogTitle("Esta é minha caixa de diálogo aberta");
        fileChooser.setFileFilter(new MyCustomFilter());
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Livros");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 46, 51), 14), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 217, 217), 8)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Titulo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 51, -1, -1));

        TextTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(TextTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 48, 507, -1));

        ButListaTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButListaTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lista.png"))); // NOI18N
        ButListaTitulo.setText("Listar");
        ButListaTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ButListaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButListaTituloActionPerformed(evt);
            }
        });
        jPanel1.add(ButListaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 33, 141, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Autor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 128, -1, -1));

        TextAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(TextAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 125, 507, -1));

        ButListaAutor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButListaAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lista.png"))); // NOI18N
        ButListaAutor.setText("Listar");
        ButListaAutor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ButListaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButListaAutorActionPerformed(evt);
            }
        });
        jPanel1.add(ButListaAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 110, 141, -1));

        Lista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaItemStateChanged(evt);
            }
        });
        jPanel1.add(Lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 184, 493, -1));

        ButPesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        ButPesquisa.setText("Pesquisar");
        ButPesquisa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ButPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(ButPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Titulos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 187, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Editora:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 238, -1, -1));

        TextEditora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(TextEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 235, 505, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Edição:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 298, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Quantidade:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        try {
            TextEdicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextEdicao.setText("00");
        TextEdicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(TextEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 59, -1));

        try {
            TextQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextQuantidade.setText("00");
        TextQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(TextQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 59, -1));

        ButGravar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Chest.gif"))); // NOI18N
        ButGravar.setText("Gravar");
        ButGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButGravarActionPerformed(evt);
            }
        });
        jPanel1.add(ButGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        ButAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pena.png"))); // NOI18N
        ButAlterar.setText("Alterar");
        ButAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(ButAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        ButExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fire.png"))); // NOI18N
        ButExcluir.setText("Excluir");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(ButExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 160, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Inserir da \nplanilha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, 57));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButGravarActionPerformed
        l.setTitulo(TextTitulo.getText());
        l.setAutor(TextAutor.getText());
        l.setEditora(TextEditora.getText());
        l.setQuantidade(Integer.parseInt(TextQuantidade.getText()));
        l.setEdicao(Integer.parseInt(TextEdicao.getText()));
        LivroManager.cadastrar(l);
    }//GEN-LAST:event_ButGravarActionPerformed

    private void ButListaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButListaTituloActionPerformed
        ArrayList<String> comp=new ArrayList<String>();
        Lista.removeAllItems();
        comp=EmprestimoManager.listar(TextTitulo.getText(),"titulo");
         if(comp.size()>=1){
            for (String vez:comp){
                Lista.addItem(vez);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Nenhum livro encontrado","Vazio",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButListaTituloActionPerformed

    private void ButListaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButListaAutorActionPerformed
        ArrayList<String> comp=new ArrayList<String>();
        Lista.removeAllItems();
        comp=EmprestimoManager.listar(TextAutor.getText(),"autor");
        if(comp.size()>=1){
            for (String vez:comp){
                Lista.addItem(vez);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Nenhum livro encontrado","Vazio",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButListaAutorActionPerformed

    private void ButPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPesquisaActionPerformed
        String temp=Lista.getSelectedItem().toString();
        l=LivroManager.pesquisar(temp.split("¬")[0], temp.split("¬")[1]);
        TextTitulo.setText(l.getTitulo());
        TextAutor.setText(l.getAutor());
        TextEditora.setText(l.getEditora());
        if(l.getQuantidade()<10){
            TextQuantidade.setText("0"+Integer.toString(l.getQuantidade()));
        }else{
            TextQuantidade.setText(Integer.toString(l.getQuantidade()));
        }
        if(l.getEdicao()<10){
            TextEdicao.setText("0"+Integer.toString(l.getEdicao()));
        }else{
            TextEdicao.setText(Integer.toString(l.getEdicao()));    
        }
        ButAlterar.setVisible(true);
        ButExcluir.setVisible(true);
        Lista.removeAllItems();
    }//GEN-LAST:event_ButPesquisaActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
        int resposta=JOptionPane.showConfirmDialog(null, "Tem certeza que quer deletar?\nSerá excluido permanentemente", "Exclusão", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION) {
            
            String respost=JOptionPane.showInputDialog(null, "Escreva 'deletar' \nignorar maiusculo e minusculo", "Confirmação", JOptionPane.QUESTION_MESSAGE);
            if(respost.equalsIgnoreCase("deletar")){
                LivroManager.deletar(l);
                l=new Livro();
                TextTitulo.setText("");
                TextAutor.setText("");
                TextEdicao.setText("");
                TextQuantidade.setText("00");
                TextEdicao.setText("00");
                ButAlterar.setVisible(false);
                ButExcluir.setVisible(false);
            }
        }
    }//GEN-LAST:event_ButExcluirActionPerformed

    private void ButAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarActionPerformed
        int resposta=JOptionPane.showConfirmDialog(null, "Tem certeza que quer subistituir?\nOs dados serão trocatos permanentemente", "Alteração", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION) {
            
            String respost=JOptionPane.showInputDialog(null, "Escreva 'sim' \nignorar maiusculo e minusculo", "Confirmação", JOptionPane.QUESTION_MESSAGE);
            if(respost.equalsIgnoreCase("sim")){ 
                l.setTitulo(TextTitulo.getText());
                l.setAutor(TextAutor.getText());
                l.setEditora(TextEditora.getText());
                l.setQuantidade(Integer.parseInt(TextQuantidade.getText()));
                l.setEdicao(Integer.parseInt(TextEdicao.getText()));
                LivroManager.atualizar(l);
                l=new Livro();
                TextTitulo.setText("");
                TextAutor.setText("");
                TextEdicao.setText("");
                TextQuantidade.setText("00");
                TextEdicao.setText("00");
                ButAlterar.setVisible(false);
                ButExcluir.setVisible(false);
            }
        }
    }//GEN-LAST:event_ButAlterarActionPerformed

    private void ListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaItemStateChanged
        try{
            Lista.setToolTipText(Lista.getSelectedItem().toString());
        }catch(NullPointerException e){
            Lista.setToolTipText("");
        }
    }//GEN-LAST:event_ListaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        CadastradorDeLivros cdl=new CadastradorDeLivros();
        cdl.setFile(file);
        cdl.start();
        /*try {
          // What to do with the file, e.g. display it in a TextArea
          
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }*/
    } else {
        System.out.println("File access cancelled by user.");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
     
    }//GEN-LAST:event_fileChooserActionPerformed
    public static void setMax(int max){
        jProgressBar1.setMaximum(max);
        jProgressBar1.setValue(0);
    }
    
    public static void inc(){
        jProgressBar1.setValue(jProgressBar1.getValue()+1);
        jProgressBar1.setToolTipText(Double.toString(  (jProgressBar1.getValue()/(float)jProgressBar1.getMaximum() )*100.0   ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterar;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButGravar;
    private javax.swing.JButton ButListaAutor;
    private javax.swing.JButton ButListaTitulo;
    private javax.swing.JButton ButPesquisa;
    private javax.swing.JComboBox Lista;
    private javax.swing.JTextField TextAutor;
    private javax.swing.JFormattedTextField TextEdicao;
    private javax.swing.JTextField TextEditora;
    private javax.swing.JFormattedTextField TextQuantidade;
    private javax.swing.JTextField TextTitulo;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
