package view;

import Model.Aluno;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.opencv.core.Mat;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class ControleAluno extends javax.swing.JFrame {
    private Aluno a;
    
    /**
     * Creates new form ControleAluno
     */
    public ControleAluno() {
        initComponents();
        ButExcluir.setVisible(false);
        ButAlterar.setVisible(false);
        a=new Aluno();
        System.load("E:/open/opencv/build/java/x86/opencv_java2410.dll");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButGravar = new javax.swing.JButton();
        ButExcluir = new javax.swing.JButton();
        ButAlterar = new javax.swing.JButton();
        TextNome = new javax.swing.JTextField();
        TextRG = new javax.swing.JFormattedTextField();
        TextEmail = new javax.swing.JTextField();
        ButPesquisarN = new javax.swing.JButton();
        TextRal = new javax.swing.JFormattedTextField();
        TextTelefone = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        ButPesquisarR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("RG:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("RA:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("E-mail:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Telefone:");

        ButGravar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButGravar.setText("Gravar");
        ButGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButGravarActionPerformed(evt);
            }
        });

        ButExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButExcluir.setText("Excluir");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });

        ButAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButAlterar.setText("Alterar");
        ButAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarActionPerformed(evt);
            }
        });

        TextNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            TextRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextEmail.setText("@fatec.sp.gov.br");

        ButPesquisarN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButPesquisarN.setText("Pesquisar");
        ButPesquisarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPesquisarNActionPerformed(evt);
            }
        });

        try {
            TextRal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextRal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            TextTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Camera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ButPesquisarR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButPesquisarR.setText("Pesquisar");
        ButPesquisarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPesquisarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButGravar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ButExcluir)
                            .addGap(18, 18, 18)
                            .addComponent(ButAlterar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextRG, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextRal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButPesquisarR)
                                .addComponent(ButPesquisarN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButPesquisarN))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButPesquisarR)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextRal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButGravar)
                    .addComponent(ButExcluir)
                    .addComponent(ButAlterar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButPesquisarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPesquisarNActionPerformed
        
        if(a.consultarPorNome(TextNome.getText())) {
            TextRG.setText(a.getRg());
            TextRal.setText(a.getRa());
            TextEmail.setText(a.getEmail());
            TextTelefone.setText(a.getTelefone());
            ButExcluir.setVisible(true);
            ButAlterar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Nome não encontrado","Vazio",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButPesquisarNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VideoCapture cam=new VideoCapture(0);
        Mat frame= new Mat();
        cam.open(0);
        cam.read(frame);
        Highgui.imwrite("qr.png",frame);
        cam.release();
        BufferedImage img = null;
        Result res=null;
        try {
            img=ImageIO.read(new FileInputStream("qr.png"));
            BinaryBitmap map=new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(img)));
            res=new MultiFormatReader().decode(map);
            String resultado=res.getText();
            //JOptionPane.showMessageDialog(null, res.getText());
            TextNome.setText(resultado.split("\n")[0]);
            TextRG.setText(resultado.split("\n")[1]);
            TextRal.setText(resultado.split("\n")[2]);
        } catch (FileNotFoundException ex) {
            System.out.println("aqui");
            //Logger.getLogger(ControleAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ControleAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotFoundException ex) {
            Logger.getLogger(ControleAluno.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButGravarActionPerformed
       a.setNome(TextNome.getText());
       a.setRg(TextRG.getText().replace(".", "").replace("-",""));
       a.setRa(TextRal.getText().replace(".", ""));
       a.setEmail(TextEmail.getText());
       a.setTelefone(TextTelefone.getText().replace("-", "").replace("(", "").replace(")",""));
       a.cadastrar();
    }//GEN-LAST:event_ButGravarActionPerformed

    private void ButPesquisarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPesquisarRActionPerformed
        
        if(a.consultarPorRa(TextRal.getText().replace(".", "")) ) {
            TextRG.setText(a.getRg());
            TextNome.setText((a.getNome()));
            TextEmail.setText(a.getEmail());
            TextTelefone.setText(a.getTelefone());
            ButExcluir.setVisible(true);
            ButAlterar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"RA não encontrado","Vazio",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButPesquisarRActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
        int resposta=JOptionPane.showConfirmDialog(null, "Tem certeza que quer deletar?\nSerá excluido permanentemente", "Exclusão", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION) {
            
            String respost=JOptionPane.showInputDialog(null, "Escreva 'deletar' \nignorar maiusculo e minusculo", "Confirmação", JOptionPane.QUESTION_MESSAGE);
            if(respost.equalsIgnoreCase("deletar")){
                a.deletar();
                a=new Aluno();
                TextNome.setText("");
                TextRG.setText("");
                TextRal.setText("");
                TextEmail.setText("@fatec.sp.gov.br");
                TextTelefone.setText("");
                ButAlterar.setVisible(false);
                ButExcluir.setVisible(false);
            }
        }
    }//GEN-LAST:event_ButExcluirActionPerformed

    private void ButAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarActionPerformed
        int resposta=JOptionPane.showConfirmDialog(null, "Tem certeza que quer subistituir?\nOs dados serão trocatos permanentemente", "Alteração", JOptionPane.YES_NO_OPTION);
        if(resposta==JOptionPane.YES_OPTION) {
            
            String respost=JOptionPane.showInputDialog(null, "Escreva 'sim' \nignorar maiusculo e minusculo", "Confirmação", JOptionPane.QUESTION_MESSAGE);
            if(respost.equalsIgnoreCase("sim")){
                a.setNome(TextNome.getText());
                a.setRg(TextRG.getText().replace(".", "").replace("-",""));
                a.setRa(TextRal.getText().replace(".", ""));
                a.setEmail(TextEmail.getText());
                a.setTelefone(TextTelefone.getText().replace("-", "").replace("(", "").replace(")",""));
                a.atualizar();
                a=new Aluno();
                TextNome.setText("");
                TextRG.setText("");
                TextRal.setText("");
                TextEmail.setText("@fatec.sp.gov.br");
                TextTelefone.setText("");
                ButAlterar.setVisible(false);
                ButExcluir.setVisible(false);
            }
        }
    }//GEN-LAST:event_ButAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterar;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButGravar;
    private javax.swing.JButton ButPesquisarN;
    private javax.swing.JButton ButPesquisarR;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextNome;
    private javax.swing.JFormattedTextField TextRG;
    private javax.swing.JFormattedTextField TextRal;
    private javax.swing.JFormattedTextField TextTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
